print()
print("Введите произвольный текст")
my_string = input()
print()
print("Количество символов в введённом тексте составляет")
print(len(my_string),"символов")
print()
print("Вывод текста в верхнем регистре")
print(my_string.upper())
print()
print("Вывод текста в нижнем регистре")
print(my_string.lower())
print()
print("Первый символ строки введенного текста")
print(my_string[0])
print()
print("Последний символ строки введенного текста")
print(my_string[-1])